app:
  name: "geolocation-service"
  version: "1.0.0"
  env: "development"

server:
  listen: ":8080"

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "admin"
  db_name: "geolocation_db"
